service: aws-s3-bucket
frameworkVersion: '3'

custom:
  s3:
    bucket: ganzo-s3-bucket

provider:
  name: aws
  runtime: nodejs16.x

  environment:
    BUCKET_NAME: ${self:custom.s3.bucket}

functions:
  # image uploader function
  createURL:
    handler: handlers/createURL.createURL
    events:
      - http:
          path: upload
          method: post
          cors: true

  getListBucket:
    handler: handlers/getListBucket.getListBucket
    events:
      - http:
          path: image
          method: get
          cors: true

  deleteImage:
    handler: handlers/deleteImage.deleteImage
    events:
      - http:
          path: image
          method: delete
          cors: true

  # s3Trigger:
  #   # this function will be triggered by when image is uploaded on AWS S3
  #   handler: handlers/s3Trigger.s3Trigger
  #   events:
  #     - s3:
  #         bucket: ${self:custom.s3.bucket}
  #         event:
  #           - s3:ObjectCreated:*
  #         # rules:
  #         #   - prefix: /
  #         #   - suffix: .jpg
  #         existing: true

resources:
  Resources:
    GanzoS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.bucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - DELETE
              AllowedOrigins:
                - '*'
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref GanzoS3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::${self:custom.s3.bucket}/*
                # For list bucket...
                - arn:aws:s3:::${self:custom.s3.bucket}
              Effect: Allow
              Principal: '*'
# CorsConfiguration
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors.html#cfn-s3-bucket-cors-corsrule
