import axios from 'axios';
import Head from 'next/head';
import React, { useState } from 'react';

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [fileData, setFileData] = useState({
    fileName: '',
    contentType: '',
  });
  const [selectedFile, setSelectedFile] = useState(null);
  const [headerType, setHeaderType] = useState('');
  const bucketName = 'ganzo-s3-bucket';

  // 1) Get image data from input
  const onGetFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files) return;

    setSelectedFile(e.target.files[0] as any);

    const contentType = e.target.files[0].type; // "image/png" will return

    setHeaderType(contentType);

    const fileName = e.target.files[0].name; // "car.png" will return

    // const fileExtension = fileName.substring(fileName.lastIndexOf('.') + 1); // "png" will return

    setFileData((prev) => ({ ...prev, fileName, contentType }));
  };

  // 2) Upload to AWS S3
  const uploadToS3 = async () => {
    setLoading(true);

    try {
      if (fileData.fileName === '')
        return alert('Please choose a file to upload first.');

      // AWS endpoint comes here...
      const endpoint =
        'https://k5nmxwqgif.execute-api.us-east-1.amazonaws.com/dev/upload';

      const response = await axios.post(endpoint, { bucketName, ...fileData });

      const preSignUrl = response.data?.preSignUrl;

      if (preSignUrl) {
        console.log(
          'PreSignURL from BACKEND>>>>>>>>',
          response.data.preSignUrl
        );

        const imgURL = await axios.put(preSignUrl, selectedFile, {
          headers: { 'Content-Type': headerType },
        });

        console.log('Finally Image URL:', imgURL);

        setLoading(false);
      }
    } catch (error: any) {
      console.log('<<<<<<ERROR FROM BACKEND>>>>:', error.message);
    } finally {
      setLoading(false);
    }
  };

  const getImageURLfromS3 = async () => {
    setLoading(true);

    try {
      // AWS endpoint comes here...
      const endpoint =
        'https://k5nmxwqgif.execute-api.us-east-1.amazonaws.com/dev/image';
      const response = await axios.get(endpoint);

      console.log(response);
    } catch (error: any) {
      console.log('<<<<<<ERROR FROM BACKEND>>>>:', error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col items-center justify-center h-screen space-y-5'>
        <input
          type='file'
          className='file-input file-input-bordered file-input-accent w-full max-w-xs '
          onChange={onGetFiles}
          max='6'
          accept='.jpg,.png,.jpeg'
          multiple
          required
        />
        <button
          className={`btn ${loading ? 'loading' : ''} `}
          onClick={uploadToS3}
        >
          UPLOAD IMAGE
        </button>
        <button
          className={`btn ${loading ? 'loading' : ''} `}
          onClick={getImageURLfromS3}
        >
          GET IMAGE URL
        </button>
      </div>
    </>
  );
}
